GET https://fifaonline4-nexon-com.translate.goog
    /3cbab51d-6f44-4569-b131-140fd3802204
    /ajax?_x_tr_sl=auto
    &_x_tr_tl=vi
    &_x_tr_hl=vi
    &_x_tr_pto=op,wapp
    &u=https%3A%2F%2Ffifaonline4.nexon.com%2FDatacenter%2FFormationVsInfo%3FstrDate%3D2022.07.23%26n1Type%3D50%26strType%3Dusage%26n4StartRanking%3D1%26n4EndRanking%3D10000%26strFormation%3D4-2-2-1-1%26rd%3D0.480994869882597